### ISSUE TITLE
Docker files for native Spark

### ISSUE THREAD

**Issue by foxish** [kubernetes/application-images#12]
The k8s-spark-native docker files can live here till we find a better location for them. 
This is single point that can be used, rather than having multiple custom images as we currently do.
I've committed here with some modifications, the files that were previously in https://github.com/erikerlandson/openshift-spark/tree/k8s-native.
Do let me know if I've missed something.

TODO:

- [ ] Clean up.
- [ ] Standardize and come up with a specification of shim scripts for people to enable building custom images.

/cc @mattf @erikerlandson @iyanuobidele @mccheah

**Comment by iyanuobidele** [comment]
Yes, we need some kind of default spark image to fall back to in our program. That can be this for now, till we find a more permanent place to move this to. 

On the same note, pardon me if this is not the best place for this, I was thinking about the best way to support proxy for users like me running behind one. Right now, I have baked it into my image at build time, which isn't really the best approach. Since we need to have a solution that works across board, I was thinking if this should be handled at image level or programatically, by playing with the JAVA_OPTS and then adding it into the container env. For more context, this is needed when the container tries to get the jar through the network url.

@foxish thoughts ?

**Comment by mccheah** [comment]
We could also look into putting the Dockerfiles in the Spark repository. I've done this here: https://github.com/foxish/spark/pull/9/files#diff-b144f9329b6d0371f44cea286a5a1046R1

Just a proposal; it's of course still unclear as to what the real right place is.

**Comment by foxish** [comment]
> Since we need to have a solution that works across board, I was thinking if this should be handled at image level or programatically, by playing with the JAVA_OPTS and then adding it into the container env.

@iyanuobidele 
That makes sense. I agree that we should be supporting specification of proxy servers, basic authentication and so on. There are two disjoint issues here. One is supporting proxies for maven package coordinates supplied using `--packages` to spark-submit. This is handled by Spark if we pass in `spark.driver.extraJavaOptions` as described [here](https://issues.apache.org/jira/browse/SPARK-11085). 

The downloading of the client-jar is currently done by a shell script which uses `curl` to download the client-jar. We need to figure out whether we're going to keep that as is, and how we can support proxies.

@mccheah's work on uploading local jars to the driver can also help this mitigate this particular issue.

**Comment by erikerlandson** [comment]
In the event that the Apache Spark upstream isn't comfortable with hosting official images, I still favor having some docker registry organization that can be managed independently of any single individual's registry acct.  I created [k8s4spark](https://hub.docker.com/u/k8s4spark/) with that idea in mind.  I'm the owner, which doesn't 100% pass the hit-by-a-bus test, however I can add administrators.
